export const googleFonts = [
  { name: 'Inter', family: "'Inter', sans-serif" },
  { name: 'Roboto', family: "'Roboto', sans-serif" },
  { name: 'Lato', family: "'Lato', sans-serif" },
  { name: 'Montserrat', family: "'Montserrat', sans-serif" },
  { name: 'Oswald', family: "'Oswald', sans-serif" },
  { name: 'Raleway', family: "'Raleway', sans-serif" },
  { name: 'Poppins', family: "'Poppins', sans-serif" },
  { name: 'Nunito', family: "'Nunito', sans-serif" },
  { name: 'Work Sans', family: "'Work Sans', sans-serif" },
  { name: 'Outfit', family: "'Outfit', sans-serif" },
  { name: 'Open Sans', family: "'Open Sans', sans-serif" },
  { name: 'Source Sans Pro', family: "'Source Sans Pro', sans-serif" },
  { name: 'PT Sans', family: "'PT Sans', sans-serif" },
  { name: 'Dosis', family: "'Dosis', sans-serif" },
  { name: 'Exo 2', family: "'Exo 2', sans-serif" },
  { name: 'Barlow', family: "'Barlow', sans-serif" },
  { name: 'Quicksand', family: "'Quicksand', sans-serif" },
  { name: 'Rubik', family: "'Rubik', sans-serif" },
  { name: 'Josefin Sans', family: "'Josefin Sans', sans-serif" },
  { name: 'Titillium Web', family: "'Titillium Web', sans-serif" },
  { name: 'Mukta', family: "'Mukta', sans-serif" },
  { name: 'Comfortaa', family: "'Comfortaa', sans-serif" },
  { name: 'Bebas Neue', family: "'Bebas Neue', cursive" },
  { name: 'Anton', family: "'Anton', sans-serif" },
  { name: 'Fjalla One', family: "'Fjalla One', sans-serif" },
  { name: 'Cabin', family: "'Cabin', sans-serif" },
  { name: 'Arvo', family: "'Arvo', serif" },
  { name: 'Lora', family: "'Lora', serif" },
  { name: 'Bitter', family: "'Bitter', serif" },
  { name: 'Crimson Text', family: "'Crimson Text', serif" },
  { name: 'Merriweather', family: "'Merriweather', serif" },
  { name: 'Playfair Display', family: "'Playfair Display', serif" },
  { name: 'Inconsolata', family: "'Inconsolata', monospace" },
  { name: 'Lobster', family: "'Lobster', cursive" },
  { name: 'Pacifico', family: "'Pacifico', cursive" },
  { name: 'Caveat', family: "'Caveat', cursive" },
  { name: 'Dancing Script', family: "'Dancing Script', cursive" },
  { name: 'Indie Flower', family: "'Indie Flower', cursive" },
];
