// This file is no longer needed for icon search and can be removed or kept for other purposes.
import type { LucideIcon } from 'lucide-react';
import * as lucideIcons from 'lucide-react';

export const icons = [
  { name: 'Rocket', icon: 'Rocket' as keyof typeof lucideIcons },
  { name: 'Brain', icon: 'BrainCircuit' as keyof typeof lucideIcons },
  { name: 'Code', icon: 'Code' as keyof typeof lucideIcons },
  { name: 'Atom', icon: 'Atom' as keyof typeof lucideIcons },
  { name: 'Feather', icon: 'Feather' as keyof typeof lucideIcons },
  { name: 'Star', icon: 'Star' as keyof typeof lucideIcons },
  { name: 'Heart', icon: 'Heart' as keyof typeof lucideIcons },
  { name: 'Sun', icon: 'Sun' as keyof typeof lucideIcons },
  { name: 'Moon', icon: 'Moon' as keyof typeof lucideIcons },
  { name: 'Cloud', icon: 'Cloud' as keyof typeof lucideIcons },
  { name: 'Leaf', icon: 'Leaf' as keyof typeof lucideIcons },
  { name: 'Flame', icon: 'Flame' as keyof typeof lucideIcons },
  { name: 'Mountain', icon: 'Mountain' as keyof typeof lucideIcons },
  { name: 'Diamond', icon: 'Gem' as keyof typeof lucideIcons },
  { name: 'Shield', icon: 'Shield' as keyof typeof lucideIcons },
  { name: 'Key', icon: 'Key' as keyof typeof lucideIcons },
  { name: 'Anchor', icon: 'Anchor' as keyof typeof lucideIcons },
  { name: 'Compass', icon: 'Compass' as keyof typeof lucideIcons },
  { name: 'Globe', icon: 'Globe' as keyof typeof lucideIcons },
  { name: 'Book', icon: 'Book' as keyof typeof lucideIcons },
  { name: 'Award', icon: 'Award' as keyof typeof lucideIcons },
  { name: 'Camera', icon: 'Camera' as keyof typeof lucideIcons },
  { name: 'Coffee', icon: 'Coffee' as keyof typeof lucideIcons },
  { name: 'Briefcase', icon: 'Briefcase' as keyof typeof lucideIcons },
  { name: 'Cpu', icon: 'Cpu' as keyof typeof lucideIcons },
  { name: 'GitBranch', icon: 'GitBranch' as keyof typeof lucideIcons },
  { name: 'MousePointer', icon: 'MousePointer' as keyof typeof lucideIcons },
  { name: 'PenTool', icon: 'PenTool' as keyof typeof lucideIcons },
  { name: 'Palette', icon: 'Palette' as keyof typeof lucideIcons },
  { name: 'Sprout', icon: 'Sprout' as keyof typeof lucideIcons },
];
